export const participantes = [
  {id: 1, participante: 'Nella Fernandez', qty: 1},
  {id: 2, participante: 'Camila Belen Fernandez', qty: 1},
  {id: 3, participante: 'Barbara Romina Gomez Solis', qty: 3},
  {id: 4, participante: 'Cecilia Calatroni', qty: 2},
  {id: 5, participante: 'Julieta Ríos', qty: 2},
  {id: 6, participante: 'Tania Alegre Rahn', qty: 1},
  {id: 7, participante: 'Florencia Noelia Ortiz', qty: 2},
  {id: 8, participante: 'Gio Pertile', qty: 2},
  {id: 9, participante: 'Juli Nievas', qty: 1},
  {id: 10, participante: 'Orlando Daniel Sosa', qty: 2},
  {id: 11, participante: 'Imanol Zalazar', qty: 11},
  {id: 12, participante: 'Maria Laura Rodriguez', qty: 1},
  {id: 13, participante: 'Fany Kus', qty: 1},
  {id: 14, participante: 'Ana Beatriz Brizuela', qty: 1},
  {id: 15, participante: 'Natalia Falcon', qty: 3},
  {id: 16, participante: 'Juli Acosta', qty: 2},
  {id: 17, participante: 'Nadia Pintos', qty: 2},
  {id: 18, participante: 'Gabriel Benitez', qty: 2},
  {id: 19, participante: 'Cristian Gabriel torres', qty: 1},
  {id: 20, participante: 'Sofia Garcia', qty: 5},
  {id: 21, participante: 'Claudia Cecilia Miranda', qty: 2},
  {id: 22, participante: 'Irene Magdalena Portillo', qty: 1},
  {id: 23, participante: 'Juan Contrera', qty: 1},
  {id: 24, participante: 'Valeria Alonso', qty: 1},
  {id: 25, participante: 'Nahuel Rusistschka', qty: 4},
  {id: 26, participante: 'Nicole Iberti', qty: 2},
  {id: 27, participante: 'Yolanda Alicia Garcia', qty: 5},
  {id: 28, participante: 'Gabriel Amado', qty: 2},
  {id: 29, participante: 'Celeste Peloso', qty: 1},
  {id: 30, participante: 'Morales Matias Maximiliano', qty: 9},
  {id: 31, participante: 'Berenice Quiroz', qty: 1},
  {id: 32, participante: 'Jorge Raul Lazatti', qty: 1},
  {id: 33, participante: 'Rocio Lopez', qty: 1},
  {id: 34, participante: 'Carballo Valentina', qty: 1},
  {id: 35, participante: 'Renzo Calabroni', qty: 2},
  {id: 36, participante: 'Rocio Maldonado', qty: 1},
  {id: 37, participante: 'Abril Camps', qty: 1},
  {id: 38, participante: 'Rodrigo Peñaflor', qty: 1},
  {id: 39, participante: 'Agos Sanchez Ruiz Diaz', qty: 1},
  {id: 40, participante: 'Cintia Lorena Ruzich', qty: 1},
  {id: 41, participante: 'Brenda Acevedo', qty: 1},
  {id: 42, participante: 'Ojeda Pablo Javier', qty: 1},
  {id: 43, participante: 'Tomi Aleman', qty: 1},
  {id: 44, participante: 'Viviana Lopez', qty: 2},
  {id: 45, participante: 'Gustavo Gabriel Rojas', qty: 1},
  {id: 46, participante: 'Beatriz pilates', qty: 2},
  {id: 47, participante: 'Vivi Gomez', qty: 3},
  {id: 48, participante: 'Martina Martegani', qty: 2},
  {id: 49, participante: 'Balcarce Enzo Daniel', qty: 1},
  {id: 50, participante: 'Meli Villalba', qty: 1},
  {id: 51, participante: 'Tiziano Yordan', qty: 1},
  {id: 52, participante: 'Guido Rivas', qty: 1},
  {id: 53, participante: 'Daiana Vargas', qty: 1},
  {id: 54, participante: 'Melisa Veron Orban', qty: 1},
  {id: 55, participante: 'Oriana Fleita', qty: 2},
  {id: 56, participante: 'Maria Cecilia Cuberli', qty: 3},
  {id: 57, participante: 'Melisa Campusano', qty: 3},
  {id: 58, participante: 'Fran Alasia', qty: 2},
  {id: 59, participante: 'Silvia Guttlein', qty: 1},
  {id: 60, participante: 'Matias Alfredo Martinez', qty: 5},
  {id: 61, participante: 'Monica Curuchet', qty: 4},
  {id: 62, participante: 'Aimara Benitez', qty: 2},
  {id: 63, participante: 'Valeria Belber', qty: 1},
  {id: 64, participante: 'Natalia Noemi Maciel', qty: 3},
  {id: 65, participante: 'Luciana Sandoval', qty: 1},
  {id: 66, participante: 'Agustina Treppo', qty: 1},
  {id: 67, participante: 'Patri Ferreyra', qty: 6},
  {id: 68, participante: 'Tere Bogatoli', qty: 1},
  {id: 69, participante: 'Leo emacora', qty: 2},
  {id: 70, participante: 'Anto Britos', qty: 2},
  {id: 71, participante: 'Edid Etel Sosa', qty: 2},
  {id: 72, participante: 'Luciana Serrano', qty: 4},
  {id: 73, participante: 'Micaela Zurano', qty: 1},
  {id: 74, participante: 'Vale Yannerich', qty: 2},
  {id: 75, participante: 'Tere Cendra', qty: 3},
  {id: 76, participante: 'Barbara Guttlein', qty: 3},
  {id: 77, participante: 'Melisa Bernal', qty: 2},
  {id: 78, participante: 'Noelia Zeniquel', qty: 1},
  {id: 79, participante: 'Jaquelin Martinez', qty: 2},
  {id: 80, participante: 'Brenda Areco', qty: 1},
  {id: 81, participante: 'Lucas Cattaneo', qty: 3},
  {id: 82, participante: 'Emiliano Gutierrez', qty: 1},
  {id: 83, participante: 'Carolina Da Silva', qty: 2},
  {id: 84, participante: 'Marita Ortiz', qty: 2},
  {id: 85, participante: 'Romina Soto', qty: 2},
  {id: 86, participante: 'Diana Zacarias', qty: 2},
  {id: 87, participante: 'Vale Falcon', qty: 1},
  {id: 88, participante: 'Mía Torres', qty: 3}
];