export const premios = [
  {id: 1, premio: '1 mes de gym gratis', auth: '@funcionaltrainingokkk'},
  {id: 2, premio: '1 regalo de @ruffi_bebe', auth: '@ruffi_bebe'},
  {id: 3, premio: '1 sesión de masajes relajantes', auth: '@puro.chakramasajes'},
  {id: 4, premio: '1 esmaltado semi permanente y 1 lifting de pestañas', auth: '@studioalba_beauty'},
  {id: 5, premio: '1 kit de productos para el cabello', auth: '@hair_inf'},
  {id: 6, premio: '1 regalo de El Clan', auth: '@el.clann'},
  {id: 7, premio: '1 mes de gym gratis', auth: '@greenclubgym'},
  {id: 8, premio: '1 regalo de La Fleur Intimates', auth: '@la_fleur_intimates'},
  {id: 9, premio: '1 regalo Valkiria Accesorios', auth: '@valkiriaccesorios__'},
  {id: 10, premio: '1 sesión de masajes', auth: '@belta_spa'},
  {id: 11, premio: '1 orden de $5000', auth: '@smartechh.arg'},
  {id: 12, premio: '1 regalo de Punto Om', auth: '@puntoo.om'},
  {id: 13, premio: '1 esmaltado semi permanente', auth: '@diazantonellayz'},
  {id: 14, premio: '1 tarta de jyq y 1 docena de empanadas de pollo frizadas', auth: '@mariangeles_galarza'},
  {id: 15, premio: '1 mes de yoga gratis', auth: '@hatha_yoga21'},
  {id: 16, premio: '1 budín verano sabor a elección', auth: '@anianiaifood'},
  {id: 17, premio: '1 sesión de reiki de roca terapias históricas', auth: 'Roca Terapias Históricas'},
  {id: 18, premio: '1 regalo de Delidrinks', auth: '@delidrinks.chaco'},
  {id: 19, premio: '1 regalo de Messirve tu ropa', auth: '@messirveturopa'},
  {id: 20, premio: '1 esmaltado semi permanente', auth: '@tusunasbyanto'},
  {id: 21, premio: '1 limpieza de cutis', auth: '@esteticakalas'},
  {id: 22, premio: '1 regalo de Despertar Aromas', auth: '@despertar.aromas'},
  {id: 23, premio: '1 regalo de @caramacchiato__', auth: '@caramacchiato__'},
  {id: 24, premio: '1 regalo de @bbasilisco_', auth: '@bbasilisco_'},
  {id: 25, premio: '1 regalo @mym_regalos', auth: '@mym_regalos'},
  {id: 26, premio: '1 esmaltado semi permanente', auth: '@carla_bazsn_nails'},
  {id: 27, premio: '1 mes de gym gratis', auth: '@harapilates'},
  {id: 28, premio: '1 picada de Fiambreria el Colono', auth: '@fiambreriaelcolono'},
  {id: 29, premio: '1 regalo de The Woof Pet', auth: '@the.woof.pet'},
]
